language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.10"
  - "0.6"

before_script:
  - npm install grunt-cli -g
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 1 # give server time to start