--- 
before_script: 
  - "npm install -g grunt-cli"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 1"
language: node_js
node_js: 
  - "0.10"
notifications: 
  slack: 
    rooms: 
      secure: sYX6frBFVfSOKh6JU007Y16zVMu4avT6oh1YDPh1rI6KLWpIKaJHjaFR+pYJYQ2D4htDOWWzxy6rz2jqyNxNtpjWNfbtRfUNv3qiMlnCPPPNflytMUDdKyfU+glLjfhQc17M3rBPoiw1sLFUx+dGAXj3Hz4dJLmzOojzeBeoJoLQWRcFVDKsYez5RahxaZzI0j9fwgWGOiflH4vGAP1JRbbqlWBHiGZ8fBpFxd/7SKWylARvoBok+L6IWEk0Uuj79IykfKEkUPNrahREtlNt5X7bYrBEDRRzFFigggWcxvzW5LZNIFA+e1XkmnXk9l0FAir2x2hgv1LGI3zfjR/kkWUg0gDYk1lBJylnSxbHWvJP+bpLqVoIqncgokxHV8+jyu377MNgCPLSFYroneh5dq32Efrz9UIIEY90zkeHgjr01Z8nGEyF/s9mzmySEq7oWAXZ+LsOyHzxHrYHisCypcBsbrOuck7mtvweVNlTXQiFzFww+Un5612vxu941GTgCFVV7qFX4vR5SrBdkkM33JDJL9SGHcNc7HKAayHfx75khQxB7WiQ1guqmaX+Uly1VfImuputeYr+JdqPk94chlN/knPOTfYmQcqpzvCWtAOtzAWmWtB/k0kHznPz8h2hNm1gEFOSqoM6MVocypHq7/ACaGGxxNYy+aYBUNOcWas=
